---
lang: zh-CN
title: ES13新特性
description: 页面的描述
---

## ES13 新特性

### 1、类字段声明

ES13 之前,类字段只能在构造函数中声明,与许多其他语言不同,我们不能在类的最外层范围内声明或定义它们,ES13 消除了这个限制

```js
<script>
class Cars {
		color = '真白';
		age = 22;
	}
const car1 = new Cars();
console.log(car1.color); //真白
console.log(car1.age);   // 22
</script>
```

### 2、私有方法和字段

以前不能在类中声明私有成员,成员通常以下划线(\_)为前缀,表示它是私有的,但仍然可以从类外部访问和修改
使用 ES13 我们现在可以将私有字段和成员添加到类中,方法是在其前面加上＃号,试图从类外部访问它们会导致错误:

```js
#firstName = "真白";
#lastName = "天天";
```

### 3、顶层 await 运算符

```js
<script>
function setTimeoutAsync(timeout){
		return new Promise((resolve) => {
			setTimeout(()=> {
				resolve();
			},timeout)
		})
	}
	await setTimeoutAsync(3000);
</script>
```

### 4、使 in 来判断某个对象是否拥有某个私有属性

```js
class Person {
  #person

  hasPerson() {
    return #person in this
  }
}

const per = new Person()
console.log(per.hasPerson()) //true
```

### 5、使用 at 函数来索引元素

```js
const arr = [1, 2, 3, 4, 5]

console.log(arr.at(-1)) //5
console.log(arr.at(1)) //2
```

### 6、Object.hasOwn()方法

在 JS 中，我们可以使用 Object.prototype.hasOwnProperty()来检查某个对象自身是否拥有某个属性:

```js
class Person {
  name = '真白'
  age = 2

  hasPerson() {
    return 'xxx'
  }
}

const per = new Person()

console.log(Object.hasOwn(per, 'name')) // true
console.log(Object.hasOwn(per, 'aaa')) // false
```

### 7、Error 对象的 Cause 属性

ES13 后，Error 对象多了一个 cause 属性来指明错误出现的原因。这个属性可以帮助我们为错误添加更多的上下文信息，从而帮助使用者们更好地定位错误。这个属性是我们在创建 error 对象时传进去的第二个参数对象的 cause 属性:

```js
function userAction() {
  try {
    apiCallThatCanThrow()
  } catch (err) {
    throw new Error('New error message', { cause: err })
  }
}

try {
  userAction()
} catch (err) {
  console.log(err)
  console.log(`Cause by: ${err.cause}`)
}
```

### 8、数组支持逆序查找

findLast()和 findLastIndex(),从数组的最后向前查找满足条件的元素,并返回本身(findLast),或返回元素所在数组的 index(findLastIndex)

```js
const found = array.findLast(item => item.value === 'xxx')
const foundIndex = array.findLastIndex(item => item.value === 'xxx')
```
